package ichttt.logicsimModLoader.config;

import javax.annotation.Nonnull;
import java.util.List;

/**
 * @since 0.0.1
 */
public abstract class ConfigElement {
    protected final int offset;

    /**
     * @since 0.0.1
     */
    public ConfigElement(int offset) {
        this.offset = offset;
    }

    /**
     * Offsets a String by the in the constructor specified value
     * @return The String with the given offset
     * @since 0.0.1
     */
    @Nonnull
    protected String offset() {
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < offset; i++) {
            builder.append("  ");
        }
        return builder.toString();
    }

    /**
     * @since 0.0.1
     * @return The lines to be written
     */
    @Nonnull
    public abstract List<String> generateLines();

    /**
     * Offsets every line generated by {@link #generateLines()}
     * @return The lines with the in the constructor specified offset
     * @since 0.0.1
     */
    @Nonnull
    public List<String> getOffsetLines() {
        List<String> lines = generateLines();
        for (int i = 0; i < lines.size(); i++) {
            lines.set(i, offset() + lines.get(i));
        }
        return lines;
    }
}
